version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: catalogo_pg
    environment:
      POSTGRES_DB: postgress
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: 4172398
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
